### ISSUE TITLE
Small issues

### ISSUE THREAD

**Issue by rbukovansky** [Perlkonig/grav-theme-knowledge-base#6]
Could you please make below shown happen? I believe it would make site look much better...
Thanks.

![kb_issues](https://cloud.githubusercontent.com/assets/1004491/23299990/ea9a1cd4-fa83-11e6-815a-e48689aa2c17.png)

**Comment by Perlkonig** [comment]
The theme uses [the Pure.css grid system](https://purecss.io/grids/). The main grids are defined in `templates/partials/base.html.twig`. Because there's no one right way to do it, I have to leave it to theme users to customize to their purpose. Be sure to follow the [Theme Inheritance docs](https://learn.getgrav.org/themes/customization#theme-inheritance) to do so.

For the title/navigation spacing, [see lines 38 and 46 of the template](https://github.com/Perlkonig/grav-theme-knowledge-base/blob/master/templates/partials/base.html.twig#L38-L46). 

For the search bar, you'll have to look closer at the simplesearch plugin CSS, because that's where the bar is pulled from.

Let me know if you have any specific questions.
